/**
 * This file is auto-generated by scripts/gen.mjs.
 * Do not make direct changes to it. Run `pnpm gen` to refresh.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a session with your API key
         * @description Exchanges your API key for session cookies (`trepa-token` and `trepa-refresh`).
         */
        post: operations["AuthController_loginApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh an expired session
         * @description Exchanges the current `trepa-refresh` cookie for a fresh `trepa-token` and a new `trepa-refresh`.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Invalidates the current refresh token and clears the auth cookies.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated user
         * @description Returns the user identified by the current session.
         */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get your user profile
         * @description Returns your user, optionally embedding related entities via `includes`.
         */
        get: operations["UsersController_find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your predictions
         * @description Returns your predictions across all pools, with filters, search, sort, and pagination.
         */
        get: operations["UsersController_findUserPredictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get your performance statistics
         * @description Returns lifetime aggregate statistics for your account.
         */
        get: operations["UsersController_getUserStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/referral-revenue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get referral revenue
         * @description Returns paginated monthly referral revenue from level 1 and level 2 volume, with all-time totals.
         */
        get: operations["UsersController_getReferralRevenue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get your portfolio
         * @description Returns a snapshot of your locked stake, realised PnL, and claimable balance.
         */
        get: operations["UsersController_getPorfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/streak-details/{streak_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get your progress in a streak
         * @description Returns your current streak count, streak rewards, and streak pool processing state.
         */
        get: operations["UsersController_getStreakDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pools
         * @description Returns paginated pools with filters, search, sorting, and optional embedded relations.
         */
        get: operations["PoolsController_findMany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a pool by ID
         * @description Returns a single pool, optionally embedding related entities via `includes`.
         */
        get: operations["PoolsController_find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a pool's predictions
         * @description Returns paginated predictions for a pool, ordered by creation date (newest first), with optional embedded relations.
         */
        get: operations["PoolsController_findPoolPredictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get pool results
         * @description Returns aggregate statistics and estimation distribution for a pool.
         */
        get: operations["PoolsController_getPoolResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get pool leaderboard
         * @description Returns a paginated, accuracy-ranked leaderboard for a resolved pool.
         */
        get: operations["PoolsController_getPoolLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/prediction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 1: Build a prediction transaction
         * @description Returns an unsigned transaction that places a prediction; sign it and submit via `POST /transactions/prediction/submit`.
         */
        post: operations["TransactionsController_createPredictionTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/prediction/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 2: Submit a signed prediction transaction
         * @description Submits the signed prediction transaction with the original `proof`.
         */
        post: operations["TransactionsController_submitPredictionTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/prediction/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 1: Build an update-prediction transaction
         * @description Returns an unsigned transaction that updates the value on an existing prediction; sign it and submit via `POST /transactions/prediction/update/submit`.
         */
        post: operations["TransactionsController_createUpdatePredictionTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/prediction/update/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 2: Submit a signed update-prediction transaction
         * @description Submits the signed update-prediction transaction with the original `proof`.
         */
        post: operations["TransactionsController_submitUpdatePredictionTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/stake/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 1: Build an update-stake transaction
         * @description Returns an unsigned transaction that updates the staked amount on an existing prediction; sign it and submit via `POST /transactions/stake/update/submit`.
         */
        post: operations["TransactionsController_createUpdateStakeTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/stake/update/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 2: Submit a signed update-stake transaction
         * @description Submits the signed update-stake transaction with the original `proof`.
         */
        post: operations["TransactionsController_submitUpdateStakeTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/claim-reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 1: Build a claim-reward transaction
         * @description Returns an unsigned transaction that claims your reward on a resolved pool; sign it and submit via `POST /transactions/claim-reward/submit`.
         */
        post: operations["TransactionsController_createClaimTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/claim-reward/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 2: Submit a signed claim-reward transaction
         * @description Submits the signed claim-reward transaction with the original `proof`.
         */
        post: operations["TransactionsController_submitClaimTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 1: Build a withdraw transaction
         * @description Returns an unsigned transaction that withdraws USDC to your external wallet; sign it and submit via `POST /transactions/withdraw/submit`.
         */
        post: operations["TransactionsController_createWithdrawTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/withdraw/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 2: Submit a signed withdraw transaction
         * @description Submits the signed withdraw transaction with the original `proof`.
         */
        post: operations["TransactionsController_submitWithdrawTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/claim-streak-reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim a streak reward on-chain
         * @description Claims a streak reward on-chain and returns the transaction signature.
         */
        post: operations["TransactionsController_claimStreakRewardTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streak/bitcoin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the Bitcoin streak
         * @description Returns the streak that powers the Bitcoin Flash product.
         */
        get: operations["StreaksController_getBitcoinStreak"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streak/pool-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current, next, and previous pools in a streak
         * @description Returns the pool currently open for predictions, the next active pool (by prediction_end_date), and the previous pool in the streak chain. Optionally embed related entities via `includes`.
         */
        get: operations["StreaksController_getPoolDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streak/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pools in a streak
         * @description Returns pools in the streak with optional `past_only` filter and pagination. Does not filter by participation.
         */
        get: operations["StreaksController_getPools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streak/user-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get your streak progress and rewards
         * @description Returns your current streak count and any streak rewards you have earned.
         */
        get: operations["StreaksController_getUserDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        UserRole: "USER" | "ADMIN";
        RedactedUserDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_seen_at: string;
            avatar_id?: string | null;
            username: string;
            twitter_username?: string | null;
            has_seen_tour: boolean;
            role: components["schemas"]["UserRole"];
            wallet_address: string;
        };
        UserDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_seen_at: string;
            avatar_id?: string | null;
            email?: string;
            username: string;
            twitter_username?: string | null;
            has_seen_tour: boolean;
            role: components["schemas"]["UserRole"];
            wallet_address: string;
        };
        ReferralRedemptionDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            referral_code_id: string;
            /** Format: date-time */
            applied_at: string;
        };
        ReferralCodeWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            code: string;
            notes?: string | null;
            user_id?: string | null;
            creator?: components["schemas"]["UserDto"];
            redemptions?: components["schemas"]["ReferralRedemptionDto"][];
        };
        ReferralRedemptionWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            referral_code_id: string;
            /** Format: date-time */
            applied_at: string;
            referral_code?: components["schemas"]["ReferralCodeWithRelationsDto"];
            user?: components["schemas"]["UserDto"];
        };
        FileDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            url: string;
        };
        /** @enum {string} */
        PoolUnit: "USD";
        /** @enum {string} */
        PoolStatus: "ACTIVE" | "PREDICTIONS_FROZEN" | "CLAIMS_FROZEN" | "FROZEN";
        ResolutionDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            pool_id: string;
            result: number;
            median?: number | null;
            protocol_fee: number;
            leftover: number;
        };
        NotificationPreferencesDto: {
            /** @default true */
            is_notifications_enabled: boolean;
            /** @default true */
            is_email_notifications_enabled: boolean;
            /** @default true */
            is_push_notifications_enabled: boolean;
            /** @default false */
            is_email_subscribe_popup_dismissed: boolean;
            /** @default true */
            POOL_CREATED: boolean;
            /** @default true */
            POOL_RESOLVED: boolean;
            /** @default true */
            POOL_REFUNDED: boolean;
            /** @default true */
            REWARD_AUTO_CLAIMED: boolean;
            /** @default true */
            STREAK_COUNT_RECEIVED: boolean;
            /** @default true */
            STREAK_COUNT_RESET: boolean;
            /** @default true */
            STREAK_REWARD_WON: boolean;
        };
        SettingsWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            notification_preferences?: components["schemas"]["NotificationPreferencesDto"];
            user?: components["schemas"]["UserDto"];
        };
        /** @enum {string} */
        NotificationType: "POOL_CREATED" | "POOL_RESOLVED" | "POOL_REFUNDED" | "REWARD_AUTO_CLAIMED" | "STREAK_COUNT_RECEIVED" | "STREAK_COUNT_RESET" | "STREAK_REWARD_WON";
        NotificationWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            title: string;
            message: string;
            type: components["schemas"]["NotificationType"];
            data?: Record<string, never>;
            /** Format: date-time */
            read_at?: string;
            user?: components["schemas"]["UserDto"];
        };
        /** @enum {string} */
        DevicePlatform: "WEB" | "IOS" | "ANDROID";
        DeviceTokenWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            token: string;
            platform: components["schemas"]["DevicePlatform"];
            user?: components["schemas"]["UserDto"];
        };
        RefreshTokenWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            version: string;
            user?: components["schemas"]["UserDto"];
        };
        ApiKeyWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            name: string;
            key_hash: string;
            is_active: boolean;
            /** Format: date-time */
            last_used_at?: string | null;
            user?: components["schemas"]["UserWithRelationsDto"];
        };
        UserWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_seen_at: string;
            avatar_id?: string | null;
            email?: string;
            username: string;
            twitter_username?: string | null;
            has_seen_tour: boolean;
            role: components["schemas"]["UserRole"];
            wallet_address: string;
            referral_redemption?: components["schemas"]["ReferralRedemptionWithRelationsDto"];
            created_referral_codes?: components["schemas"]["ReferralCodeWithRelationsDto"][];
            avatar?: components["schemas"]["FileDto"];
            pools?: components["schemas"]["PoolWithRelationsDto"][];
            settings?: components["schemas"]["SettingsWithRelationsDto"];
            notifications?: components["schemas"]["NotificationWithRelationsDto"][];
            device_tokens?: components["schemas"]["DeviceTokenWithRelationsDto"][];
            refresh_tokens?: components["schemas"]["RefreshTokenWithRelationsDto"][];
            predictions?: components["schemas"]["PredictionWithRelationsDto"][];
            api_keys?: components["schemas"]["ApiKeyWithRelationsDto"][];
        };
        /** @enum {string} */
        RewardType: "REWARD" | "REFUND";
        RewardDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            prediction_id: string;
            amount: number;
            precision_score: number;
            is_claimed: boolean;
            type: components["schemas"]["RewardType"];
        };
        StreakDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            last_processed_pool_id: Record<string, never> | null;
            streak_accumulator_account: string;
            title: string;
            /** @example 5 */
            fee_percentage: number;
            bump: number;
            streak_count_required: number;
            min_precision_score_required: number;
            total_accumulated: number;
            available_balance: number;
            onchain_balance: number;
            /** Format: date-time */
            last_sync_at: string;
        };
        PredictionWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            pool_account: string;
            predictor_account: string;
            prediction_account: string;
            prediction: number;
            precision: number;
            stake_token_mint: string;
            stake: number;
            decimals: number;
            last_applied_value_revision: number;
            last_applied_stake_revision: number;
            is_fee_payer: boolean;
            is_closed: boolean;
            bump: number;
            /** Format: date-time */
            last_sync_at: string;
            user?: components["schemas"]["UserWithRelationsDto"];
            pool?: components["schemas"]["PoolWithRelationsDto"];
            reward?: components["schemas"]["RewardDto"];
            streak?: components["schemas"]["StreakDto"];
        };
        StreakWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            last_processed_pool_id: Record<string, never> | null;
            streak_accumulator_account: string;
            title: string;
            /** @example 5 */
            fee_percentage: number;
            bump: number;
            streak_count_required: number;
            min_precision_score_required: number;
            total_accumulated: number;
            available_balance: number;
            onchain_balance: number;
            /** Format: date-time */
            last_sync_at: string;
        };
        PoolWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            created_by: string | null;
            image_id: string | null;
            streak_id: string | null;
            title: string;
            description: string | null;
            pool_account: string;
            resolution_source: string;
            unit: components["schemas"]["PoolUnit"];
            min_stake: number;
            max_stake: number;
            max_roi: number;
            stake_token_mint: string;
            decimals: number;
            min_outcome: number;
            max_outcome: number;
            precision: number;
            step: number;
            /** Format: date-time */
            prediction_start_date: string;
            /** Format: date-time */
            prediction_end_date: string;
            /** Format: date-time */
            reference_date: string;
            status: components["schemas"]["PoolStatus"];
            is_closed: boolean;
            platform_fee_rate?: number | null;
            indexed_prediction_update_count: number;
            readonly total_volume?: number | null;
            user?: components["schemas"]["UserDto"];
            resolution?: components["schemas"]["ResolutionDto"];
            image?: components["schemas"]["FileDto"];
            predictions?: components["schemas"]["PredictionWithRelationsDto"][];
            streak?: components["schemas"]["StreakWithRelationsDto"];
        };
        CreateUserApiKeyDto: {
            name: string;
            is_active: boolean;
            /** Format: date-time */
            last_used_at?: string | null;
        };
        CreateUserApiKeyResponseDto: {
            api_key: string;
        };
        ApiKeyDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            name: string;
            key_hash: string;
            is_active: boolean;
            /** Format: date-time */
            last_used_at?: string | null;
        };
        /** @enum {string} */
        FilterPredictionsBy: "ACTIVE" | "CLAIMABLE";
        /** @enum {string} */
        SortPredictionsBy: "CREATION_DATE" | "RESOLUTION_DATE";
        LimitedUpdateUserDto: {
            avatar_id?: string | null;
            username?: string;
            has_seen_tour?: boolean;
        };
        ReferralCodeDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            code: string;
            notes?: string | null;
            user_id?: string | null;
        };
        ValidateReferralDto: {
            code: string;
        };
        SettingsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            notification_preferences?: components["schemas"]["NotificationPreferencesDto"];
        };
        UpdateSettingsDto: {
            user_id?: string;
            notification_preferences?: components["schemas"]["NotificationPreferencesDto"];
        };
        /** @enum {string} */
        SortLeaderboardBy: "ROI" | "PNL" | "PRECISION";
        /** @enum {string} */
        LeaderboardTimeframe: "DAILY" | "WEEKLY" | "MONTHLY" | "ALL_TIME";
        LeaderboardEntryDto: {
            user_id: string;
            username: string;
            twitter_username?: string | null;
            avatar_url: Record<string, never>;
            total_roi: Record<string, never>;
            total_pnl: Record<string, never>;
            total_precision_score: Record<string, never>;
            roi_rank: number;
            pnl_rank: number;
            precision_rank: number;
        };
        UserStatisticsDto: {
            volume: number;
            wins: number;
            losses: number;
            predictions: number;
            win_rate: number;
            days_active: number;
            /** Format: date-time */
            date_joined: string;
        };
        ReferralRevenueDto: {
            user_id: string;
            /** Format: date-time */
            period_start: string;
            /** Format: date-time */
            period_end: string;
            level_1_referred_users_added: number;
            level_2_referred_users_added: number;
            referred_users_added: number;
            level_1_referred_volume: number;
            level_2_referred_volume: number;
            referred_user_volume: number;
            /**
             * @description Referral revenue tier for the period.
             * @enum {string}
             */
            revenue_tier: "BRONZE" | "SILVER" | "GOLD" | "PLATINUM";
            /** @description Level 1 revenue rate for the period. */
            level_1_revenue_rate: number;
            /** @description Level 2 revenue rate for the period. */
            level_2_revenue_rate: number;
            /** @description Eligible revenue for the period. */
            eligible_payout: number;
        };
        ReferralRevenueRateDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            effective_from: string;
            bronze_min_network_volume: number;
            silver_min_network_volume: number;
            gold_min_network_volume: number;
            platinum_min_network_volume: number;
            bronze_level_1_revenue_rate: number;
            bronze_level_2_revenue_rate: number;
            silver_level_1_revenue_rate: number;
            silver_level_2_revenue_rate: number;
            gold_level_1_revenue_rate: number;
            gold_level_2_revenue_rate: number;
            platinum_level_1_revenue_rate: number;
            platinum_level_2_revenue_rate: number;
        };
        ReferralRevenueResponseDto: {
            periods: components["schemas"]["ReferralRevenueDto"][];
            all_time_referred_user_count: number;
            all_time_level_1_referred_user_count: number;
            all_time_level_2_referred_user_count: number;
            all_time_referred_user_volume: number;
            all_time_eligible_payout: number;
            all_time_level_1_eligible_payout: number;
            all_time_level_2_eligible_payout: number;
            all_time_level_1_referred_volume: number;
            all_time_level_2_referred_volume: number;
            /** @enum {string} */
            revenue_tier: "BRONZE" | "SILVER" | "GOLD" | "PLATINUM";
            /** @enum {string} */
            current_period_revenue_tier: "BRONZE" | "SILVER" | "GOLD" | "PLATINUM";
            all_time_network_volume: number;
            level_1_revenue_rate: number;
            level_2_revenue_rate: number;
            tier_program?: components["schemas"]["ReferralRevenueRateDto"] | null;
        };
        PortfolioDto: {
            staked_amount: number;
            claimed_amount: number;
            unclaimed_amount: number;
        };
        /** @enum {string} */
        FilterPnlBy: "1D" | "1W" | "1M" | "3M" | "ALL";
        PnlChartDataPointDto: {
            /** Format: date-time */
            date: string;
            value: number;
        };
        PnlDto: {
            total_profit: number;
            total_loss: number;
            net_profit: number;
            roi_percent: number | null;
            chart_data: components["schemas"]["PnlChartDataPointDto"][];
        };
        NotificationCountDto: {
            unread: number;
        };
        /** @enum {string} */
        FilterNotificationsBy: "READ" | "UNREAD";
        NotificationDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            title: string;
            message: string;
            type: components["schemas"]["NotificationType"];
            data?: Record<string, never>;
            /** Format: date-time */
            read_at?: string;
        };
        /** @enum {string} */
        TransactionType: "DEPOSIT" | "WITHDRAWAL" | "STAKING" | "REWARD";
        /** @enum {string} */
        TransactionStatus: "SUCCESS" | "FAILED";
        TransactionHistoryItemDto: {
            id: string;
            type: components["schemas"]["TransactionType"];
            amount: number;
            counterparty: string;
            /** Format: date-time */
            timestamp: string;
            status: components["schemas"]["TransactionStatus"];
        };
        TransactionHistoryResponseDto: {
            transactions: components["schemas"]["TransactionHistoryItemDto"][];
            has_more: boolean;
            next_cursor?: Record<string, never>;
        };
        /** @enum {string} */
        StreakEvent: "NONE" | "QUALIFIED" | "RESET" | "REWARDED";
        StreakRewardWithRelationsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            streak_id: string;
            user_wallet_address: string;
            amount: number;
            is_claimed: boolean;
            streak?: components["schemas"]["StreakWithRelationsDto"];
        };
        StreakDetailsDto: {
            streak: components["schemas"]["StreakDto"];
            current_streak_count: number;
            last_pool_participated_at?: Record<string, never>;
            last_streak_event: components["schemas"]["StreakEvent"];
            streak_rewards?: components["schemas"]["StreakRewardWithRelationsDto"][];
            current_streak_scores?: number[];
            /** Format: uuid */
            last_processed_pool_id?: string | null;
        };
        CreateNewPoolDto: {
            min_outcome: number;
            max_outcome: number;
            /** Format: date-time */
            prediction_start_date: string;
            /** Format: date-time */
            prediction_end_date: string;
            /** Format: date-time */
            reference_date: string;
            streak_id: string;
        };
        Job: Record<string, never>;
        /** @enum {string} */
        AutoBatchPoolStatus: "QUEUED" | "SKIPPED" | "FAILED";
        CleanupPoolResultDto: {
            pool_id: string;
            status: components["schemas"]["AutoBatchPoolStatus"];
            job_id?: string;
            error?: string;
            skip_reason?: string;
        };
        CleanupPoolsResponseDto: {
            total_found: number;
            total_eligible: number;
            successfully_queued: number;
            failed: number;
            skipped: number;
            results: components["schemas"]["CleanupPoolResultDto"][];
        };
        /** @enum {string} */
        SortPoolsBy: "END_DATE" | "CREATION_DATE" | "OLD_CREATION_DATE" | "VOLUME_HIGH" | "VOLUME_LOW";
        /** @enum {string} */
        FilterPoolsBy: "ACTIVE" | "ENDED" | "RESOLVED" | "NOT_RESOLVED";
        /** @enum {string} */
        ALL_POOL_RELATIONS: "user" | "resolution" | "image" | "predictions" | "streak";
        MechanismRewardDto: {
            address: string;
            value: number;
            stake: number;
            return: number;
            roi: number;
            precision_score: number;
            error: number;
        };
        ResolutionPreviewDto: {
            /** Format: uuid */
            pool_id: string;
            /** Format: date-time */
            reference_date: string;
            outcome: number;
            winners: components["schemas"]["MechanismRewardDto"][];
            losers: components["schemas"]["MechanismRewardDto"][];
            refunds: components["schemas"]["MechanismRewardDto"][];
            median: number;
            total_participants: number;
            last_winner_error?: Record<string, never> | null;
            best_return?: Record<string, never> | null;
            worst_return?: Record<string, never> | null;
            user_rank?: Record<string, never> | null;
        };
        /** @enum {string} */
        ALL_PREDICTION_RELATIONS: "user" | "pool" | "reward" | "streak" | "pool.image" | "pool.resolution";
        CrowdPredictionDto: {
            id: string;
            prediction: number;
            stake: number;
        };
        PoolCrowdDto: {
            predictions: components["schemas"]["CrowdPredictionDto"][];
            /** Format: date-time */
            server_time: string;
        };
        CrowdCurveDto: {
            price_min: number;
            price_max: number;
            densities: number[];
        };
        PoolResultsDto: {
            winning_range: number[] | null;
            prediction_range: number[] | null;
            total_predictors_count: number;
            total_stake: number;
            outcome: Record<string, never> | null;
            unit: components["schemas"]["PoolUnit"];
            decimals: number;
            precision: number;
            min_outcome: number;
            max_outcome: number;
            precision_score_weighted_average: Record<string, never> | null;
            crowd_signal_accuracy: Record<string, never> | null;
        };
        PoolLeaderboardUserEntryDto: {
            title: string;
            username: string;
            twitter_username?: string | null;
            user_accuracy: number;
            user_value: number;
            actual_value: number;
            stake: number;
            reward: number;
            profit: number;
            roi: number;
            precision_score: number;
            rank: number;
            is_winner: boolean;
            is_refund: boolean;
        };
        PoolLeaderboardEntryDto: {
            rank: number;
            username: string;
            twitter_username?: string | null;
            avatar_url: Record<string, never>;
            accuracy: number;
            value: number;
            stake: number;
            reward: number;
            profit: number;
            roi: number;
            is_refund: boolean;
        };
        MechanismPayoutSampleDto: {
            outcome: number;
            payout: number;
        };
        MechanismUserPayoutSimulationDto: {
            address: string;
            stake: number;
            prediction: number;
            samples: components["schemas"]["MechanismPayoutSampleDto"][];
        };
        MechanismPayoutSimulationDto: {
            outcome_center: number;
            simulation_range_min: number;
            simulation_range_max: number;
            sample_count: number;
            users: components["schemas"]["MechanismUserPayoutSimulationDto"][];
        };
        MechanismUserWinningRangeDto: {
            address: string;
            value: number;
            min: Record<string, never> | null;
            max: Record<string, never> | null;
        };
        TemplateDto: {
            id: string;
            title: string;
            description: string;
            resolution_source: string;
            unit: components["schemas"]["PoolUnit"];
            precision: number;
            step: number;
        };
        CreatePredictionTransactionDto: {
            pool_id: string;
            stake: number;
            value: number;
        };
        PredictionTransactionDto: {
            transaction: string;
            proof: string;
        };
        SubmitPredictionTransactionDto: {
            pool_id: string;
            signed_transaction: string;
            proof: string;
        };
        SubmittedPredictionTransactionDto: {
            signature: string;
        };
        CreateUpdatePredictionTransactionDto: {
            prediction_id: string;
            value: number;
        };
        SubmitUpdatePredictionTransactionDto: {
            prediction_id: string;
            signed_transaction: string;
            proof: string;
        };
        CreateUpdateStakeTransactionDto: {
            prediction_id: string;
            stake: number;
        };
        SubmitUpdateStakeTransactionDto: {
            prediction_id: string;
            signed_transaction: string;
            proof: string;
        };
        CreateClaimTransactionDto: {
            pool_id: string;
        };
        ClaimTransactionDto: {
            transaction: string;
            proof: string;
        };
        SubmitClaimTransactionDto: {
            reward_id: string;
            signed_transaction: string;
            proof: string;
        };
        SubmittedClaimTransactionDto: {
            signature: string;
            reward: components["schemas"]["RewardDto"];
        };
        CreateWithdrawTransactionDto: {
            to_address: string;
            amount: number;
        };
        WithdrawTransactionDto: {
            transaction: string;
            proof: string;
        };
        SubmitWithdrawTransactionDto: {
            to_address: string;
            amount: number;
            signed_transaction: string;
            proof: string;
        };
        SubmittedWithdrawTransactionDto: {
            signature: string;
        };
        ClaimStreakRewardTransactionDto: {
            streak_reward_id: string;
        };
        StreakRewardDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            streak_id: string;
            user_wallet_address: string;
            amount: number;
            is_claimed: boolean;
        };
        SubmittedClaimStreakRewardTransactionDto: {
            signature: string;
            streak_reward: components["schemas"]["StreakRewardDto"];
        };
        RegisterDeviceTokenDto: {
            token: string;
            platform: components["schemas"]["DevicePlatform"];
        };
        DeviceTokenDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            token: string;
            platform: components["schemas"]["DevicePlatform"];
        };
        /** @enum {string} */
        ProgramConfigStatus: "ACTIVE" | "FROZEN";
        ProgramConfigsDto: {
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            config_account: string;
            admin_address: string;
            platform_fee_bps: number;
            treasury_address: string;
            creator_address: string;
            resolver_address: string;
            pending_creator_address: string;
            pending_resolver_address: string;
            self_claim_window: number;
            bump: number;
            status: components["schemas"]["ProgramConfigStatus"];
        };
        StreakBitcoinDto: {
            id: string;
            title: string;
            streak_count_required: number;
            min_precision_score_required: number;
            available_balance: number;
        };
        StreakPoolDetailsDto: {
            current_pool?: components["schemas"]["PoolWithRelationsDto"] | null;
            next_pool?: components["schemas"]["PoolWithRelationsDto"] | null;
            previous_pool?: components["schemas"]["PoolWithRelationsDto"] | null;
        };
        StreakPoolsListDto: {
            /** @description All pools linked to the streak */
            pools: components["schemas"]["PoolWithRelationsDto"][];
        };
        UpdateStreakFeePercentageDto: {
            /** @example 5 */
            fee_percentage: number;
        };
        UpdateStreakFeePercentageResponseDto: {
            signature: string;
            /** @example 5 */
            fee_percentage: number;
        };
        StreakTopUpResponseDto: {
            topped_up: boolean;
            amount?: number;
            signature?: string;
        };
        CreateStreakDto: {
            title: string;
            /** @example 5 */
            fee_percentage: number;
            streak_count_required: number;
            min_precision_score_required: number;
        };
        DominoApiKeyDto: {
            key: string;
        };
        DominoUserPredictionsResponseDto: {
            total_predictions: number;
        };
        DominoUserDepositsResponseDto: {
            total_deposited: number;
        };
        CreateReferralRevenueRateDto: {
            /** Format: date-time */
            effective_from: string;
            bronze_min_network_volume: number;
            silver_min_network_volume: number;
            gold_min_network_volume: number;
            platinum_min_network_volume: number;
            bronze_level_1_revenue_rate: number;
            bronze_level_2_revenue_rate: number;
            silver_level_1_revenue_rate: number;
            silver_level_2_revenue_rate: number;
            gold_level_1_revenue_rate: number;
            gold_level_2_revenue_rate: number;
            platinum_level_1_revenue_rate: number;
            platinum_level_2_revenue_rate: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_loginApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session has been established successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or missing API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The access token has been refreshed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The refresh token has been invalid or expired. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The access token has been invalidated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user has been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedactedUserDto"];
                };
            };
            /** @description The authentication has failed. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_find: {
        parameters: {
            query?: {
                includes?: ("referral_redemption" | "created_referral_codes" | "avatar" | "pools" | "settings" | "notifications" | "device_tokens" | "refresh_tokens" | "predictions" | "api_keys" | "referral_redemption.referral_code" | "referral_redemption.referral_code.creator" | "created_referral_codes.redemptions" | "created_referral_codes.redemptions.user" | "predictions.reward")[];
            };
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user data has been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithRelationsDto"];
                };
            };
            /** @description You are not authorized to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user has not been found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findUserPredictions: {
        parameters: {
            query?: {
                filter_by?: components["schemas"]["FilterPredictionsBy"][];
                sort_by?: components["schemas"]["SortPredictionsBy"];
                streak_id?: string;
                past_only?: boolean;
                query?: string;
                offset?: number;
                limit?: number;
                includes?: ("user" | "pool" | "reward" | "streak" | "pool.image" | "pool.resolution")[];
            };
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The predictions have been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionWithRelationsDto"][];
                };
            };
            /** @description You are not authorized to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getUserStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user statistics have been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatisticsDto"];
                };
            };
            /** @description You are not authorized to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getReferralRevenue: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Referral revenue periods have been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralRevenueResponseDto"];
                };
            };
            /** @description You are not authorized to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User or referral revenue not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getPorfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The portfolio has been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDto"];
                };
            };
            /** @description You are not authorized to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getStreakDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
                /** @description Streak identifier */
                streak_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The streak details have been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakDetailsDto"];
                };
            };
            /** @description You are not authorized to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User or streak not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PoolsController_findMany: {
        parameters: {
            query?: {
                sort_by?: components["schemas"]["SortPoolsBy"];
                filter_by?: components["schemas"]["FilterPoolsBy"][];
                reference_date?: string;
                streak_id?: string;
                query?: string;
                offset?: number;
                limit?: number;
                includes?: components["schemas"]["ALL_POOL_RELATIONS"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pools have been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolWithRelationsDto"][];
                };
            };
        };
    };
    PoolsController_find: {
        parameters: {
            query?: {
                includes?: components["schemas"]["ALL_POOL_RELATIONS"][];
            };
            header?: never;
            path: {
                /** @description Pool identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pool has been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolWithRelationsDto"];
                };
            };
            /** @description The pool has not been found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PoolsController_findPoolPredictions: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                includes?: components["schemas"]["ALL_PREDICTION_RELATIONS"][];
            };
            header?: never;
            path: {
                /** @description Pool identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pool's predictions have been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionWithRelationsDto"][];
                };
            };
            /** @description The pool has not been found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PoolsController_getPoolResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pool identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pool results have been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolResultsDto"];
                };
            };
            /** @description The pool has not been found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PoolsController_getPoolLeaderboard: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Pool identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pool leaderboard has been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolLeaderboardEntryDto"][];
                };
            };
            /** @description The pool has not been found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_createPredictionTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePredictionTransactionDto"];
            };
        };
        responses: {
            /** @description The prediction transaction has been created successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionTransactionDto"];
                };
            };
            /** @description The user has already made a prediction for this pool. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The pool has not been found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_submitPredictionTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitPredictionTransactionDto"];
            };
        };
        responses: {
            /** @description The prediction transaction has been submitted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedPredictionTransactionDto"];
                };
            };
            /** @description The user has already made a prediction for this pool. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The pool has not been found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_createUpdatePredictionTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUpdatePredictionTransactionDto"];
            };
        };
        responses: {
            /** @description The update prediction transaction has been created successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionTransactionDto"];
                };
            };
            /** @description The prediction has not been found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_submitUpdatePredictionTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitUpdatePredictionTransactionDto"];
            };
        };
        responses: {
            /** @description The update prediction transaction has been submitted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedPredictionTransactionDto"];
                };
            };
        };
    };
    TransactionsController_createUpdateStakeTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUpdateStakeTransactionDto"];
            };
        };
        responses: {
            /** @description The update stake transaction has been created successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionTransactionDto"];
                };
            };
            /** @description The prediction or pool has not been found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_submitUpdateStakeTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitUpdateStakeTransactionDto"];
            };
        };
        responses: {
            /** @description The update stake transaction has been submitted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedPredictionTransactionDto"];
                };
            };
        };
    };
    TransactionsController_createClaimTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClaimTransactionDto"];
            };
        };
        responses: {
            /** @description The claim transaction has been created successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimTransactionDto"];
                };
            };
            /**
             * @description The reward for this prediction has already been claimed or does not exist.
             *
             *     The user has not made a prediction for this pool.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The pool has not been found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_submitClaimTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitClaimTransactionDto"];
            };
        };
        responses: {
            /** @description The claim transaction has been submitted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedClaimTransactionDto"];
                };
            };
            /** @description The reward for this prediction has already been claimed or does not exist. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_createWithdrawTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWithdrawTransactionDto"];
            };
        };
        responses: {
            /** @description The withdraw transaction has been created successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawTransactionDto"];
                };
            };
            /** @description Withdrawal amount is below the $1 minimum. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_submitWithdrawTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitWithdrawTransactionDto"];
            };
        };
        responses: {
            /** @description The withdraw transaction has been submitted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedWithdrawTransactionDto"];
                };
            };
        };
    };
    TransactionsController_claimStreakRewardTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimStreakRewardTransactionDto"];
            };
        };
        responses: {
            /** @description The streak reward has been claimed successfully on-chain. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedClaimStreakRewardTransactionDto"];
                };
            };
            /** @description No unclaimed streak reward found, or a claim is already in progress. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StreaksController_getBitcoinStreak: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bitcoin streak has been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakBitcoinDto"];
                };
            };
            /** @description No streak found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StreaksController_getPoolDetails: {
        parameters: {
            query: {
                /** @description Streak UUID */
                streak_id: string;
                includes?: components["schemas"]["ALL_POOL_RELATIONS"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pool details have been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakPoolDetailsDto"];
                };
            };
            /** @description Streak not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StreaksController_getPools: {
        parameters: {
            query: {
                /** @description Streak UUID */
                streak_id: string;
                offset?: number;
                limit?: number;
                participated_only?: boolean;
                past_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pools have been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakPoolsListDto"];
                };
            };
            /** @description Streak not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StreaksController_getUserDetails: {
        parameters: {
            query: {
                /** @description Streak UUID */
                streak_id: string;
                offset?: number;
                limit?: number;
                /** @description Filter rewards by claimed status */
                is_claimed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User streak details have been retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakDetailsDto"];
                };
            };
            /** @description Streak or user not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
