#!/usr/bin/env node
/**
 * Generates `src/api/schema.ts` from `openapi.json`, but first strips any
 * operation flagged with the `x-excluded: true` vendor extension (set by the
 * API's `@ApiExcludeFromPublicDocs()` decorator). The resulting schema only
 * exposes endpoints that are part of the documented public surface — both
 * the resource methods AND `trepa.raw` are then bound to the same path set.
 */

import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const HTTP_METHODS = [
	'get',
	'put',
	'post',
	'delete',
	'options',
	'head',
	'patch',
	'trace',
]

const root = fileURLToPath(new URL('..', import.meta.url))
const inputPath = new URL('../openapi.json', import.meta.url)
const outputPath = new URL('../src/api/schema.ts', import.meta.url)

const spec = JSON.parse(await readFile(inputPath, 'utf8'))

let removedOps = 0
let removedPaths = 0
for (const [pathKey, pathItem] of Object.entries(spec.paths ?? {})) {
	if (!pathItem || typeof pathItem !== 'object') continue
	for (const method of HTTP_METHODS) {
		const op = pathItem[method]
		if (op && op['x-excluded'] === true) {
			delete pathItem[method]
			removedOps++
		}
	}
	if (!HTTP_METHODS.some((m) => pathItem[m])) {
		delete spec.paths[pathKey]
		removedPaths++
	}
}

const ast = await openapiTS(spec, {
	cwd: new URL(`file://${root}`),
	silent: true,
})
const ts = astToString(ast)
const banner =
	'/**\n' +
	' * This file is auto-generated by scripts/gen.mjs.\n' +
	' * Do not make direct changes to it. Run `pnpm gen` to refresh.\n' +
	' */\n\n'
await writeFile(outputPath, banner + ts)
console.log(
	`gen: ${removedOps} private operation(s) and ${removedPaths} now-empty path(s) excluded from the generated schema`,
)
